name: Publish & Release

on:
  push:
    branches: [master]

jobs:
  publish-release:
    runs-on: ubuntu-22.04
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      GH_REPOSITORY: ${{ github.repository }}
      NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      VERBOSE: 1
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'
          registry-url: 'https://registry.npmjs.org'

      - run: mv $NPM_CONFIG_USERCONFIG ${{ github.workspace }}/.npmrc

      - run: npm ci

      - run: npm run build

      - name: Release
        run: node ./bin/release.js -i 1.0.0
